name: union
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  email_validator: ^2.0.1
  responsive_grid: ^2.1.0
  mask_text_input_formatter: ^2.3.0
  cpf_cnpj_validator: ^2.0.0
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/union.png
    - images/hands.png
    - images/dialog.png
    - images/user.png
    - images/man_person.png
    - images/woman_person.png
    - images/square.png
    - images/vinicius.png
    - images/amanda.png
    - images/cvv.png
